### ISSUE TITLE
[Feature Request] : Add support for bloom model apdaters

### ISSUE THREAD

**Issue by Saugatkafley** [predibase/lorax#152]
### Model description

I am trying to run bloom-7b1 model using docker locally [both my model and adpters ]. Here is the script for running bloom on , lorax: 
```shell
#!bin/bash
# PATH to model 
model="bloom-7b1"
# VOLUME to share: pwd/../models -> /data
volume=$PWD/../models:/data # share a volume with the Docker container to avoid downloading weights every run
echo $volume

docker run --gpus 0 --shm-size 1g -p 7070:80 \
    --volume $volume \
    ghcr.io/predibase/lorax:latest \
    --model-id /data/$model \
    --num-shard 1 \
    --quantize bitsandbytes-nf4 \
    --max-concurrent-requests 256 \
    --cuda-memory-fraction 0.5 \
``` 
WHen I pass the adapter located at `peft-models/bloom-alpaca-ne` 
`Screenshot`:
![image](https://github.com/predibase/lorax/assets/52364337/e8e74eeb-f0f0-45a5-a215-a49e8d940f7d)
![image](https://github.com/predibase/lorax/assets/52364337/89c80305-105f-499b-9d32-f7c56751a3e9)

### Open source status

- [ ] The model implementation is available
- [X] The model weights are available

**Comment by tgaddair** [comment]
Hi @Saugatkafley, apologies for the late response, I was on holiday last week.

This should hopefully be pretty straightforward to do. I can try and get it in some time next week.

**Comment by Saugatkafley** [comment]
Hi @tgaddair, i am eagerly waiting for bloom model support.

**Comment by tgaddair** [comment]
Sorry for the delay on this @Saugatkafley! I'll try and get to this this week. I should have some time opening up tomorrow or Thursday.
