### ISSUE TITLE
Punica kernel build fails 

### ISSUE THREAD

**Issue by joaopcm1996** [predibase/lorax#153]
I am trying to rebuild the Lorax docker image, which is failing in the punica-builder stage. Error logs are attached, could you advise? 

My final goal is to make Lorax deployable on Sagemaker by adding back the entrypoint for a sagemaker stage which [was originally](https://github.com/huggingface/text-generation-inference/blob/9f18f4c00627e1a0ad696b6774e5ad7ca8f4261c/Dockerfile#L206) in the Dockerfile.

Thanks.

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

`docker build --target base -t lorax:base`
[build.log](https://github.com/predibase/lorax/files/13795700/build.log)

### Expected behavior

Successfull docker build.

**Comment by tgaddair** [comment]
Hey @joaopcm1996, thanks for providing the full logs. The error message seems to suggest that the `flashinfer` submodule can't be found locally. You should be able to fix this by running the following from the root of the `lorax` repo before calling `docker build ...`:

```
git submodule update --init
```

Double-check that the directory exists:

```
ls server/punica_kernels/third_party/flashinfer
```

**Comment by joaopcm1996** [comment]
That solved it, thanks!

**Comment by dstripelis** [comment]
Hello @tgaddair, is it possible to add the `git submodule update --init` on the README file or as part of the [build.sh](https://github.com/predibase/lorax/blob/main/build.sh) so that it is easier for newcomers to build the image from scratch?
