### ISSUE TITLE
Support weighted adapters

### ISSUE THREAD

**Issue by tgaddair** [predibase/lorax#159]
Allow users to provide a weighted listed of adapters per request:

```
parameters: {
    "adapter_weights": {"foo": 0.75, "bar": 0.25}
}
```

This parameter would be mutually exclusive with the existing `adapter_id` parameter (taking a single adapter).

**Comment by codybum** [comment]
Yes, this would be a fantastic addition, we currently have to merge the weights and save an adapter.

**Comment by tgaddair** [comment]
Thanks @codybum for the validation of this feature! Would love to hear more about your use case some time.

My hope is I should be able to get to this one some time next week if all goes to plan.

**Comment by codybum** [comment]
Hi @tgaddair, We train various lora modules independently, and at times with different lora configurations.  We use it like a poor man's MoE, where we weight the experts statically in different estimator trials, and based on the results we merge the best performing configuration.   It would be nice to be able to do this dynamically per question.  

There are a few projects out there exploring this area: 
LMoE: https://github.com/jondurbin/airoboros?tab=readme-ov-file#lmoe  
LoraHub: https://github.com/sail-sg/lorahub

Thanks for the great work!

**Comment by tgaddair** [comment]
Hey @codybum, apologies this took longer than expected, but we now support linear, TIES, and DARE merging per request!

Here are the docs: https://predibase.github.io/lorax/guides/merging_adapters/

**Comment by codybum** [comment]
@tgaddair that is fantastic!  We just submitted a conference paper last night that makes use of LoRAX for multi-lora inferencing.  I submitted to arXiv as well this morning.  I will post it when the arXiv link is up.

The per-request effort is critical to a paper we will be submitting next month.

Thanks!

**Comment by codybum** [comment]
@tgaddair 

https://arxiv.org/abs/2402.00913

Our latest paper, "Institutional Platform for Secure Self-Service Large Language Model Exploration", has been posted to arXiv.

Abstract—This paper introduces a user-friendly platform developed by the University of Kentucky Center for Applied AI, designed to make large, customized language models (LLMs) more accessible. By capitalizing on recent advancements in multi-LoRA inference, the system efficiently accommodates custom adapters for a diverse range of users and projects. The paper outlines the system’s architecture and key features, encompassing dataset curation, model training, secure inference, and text-based feature extraction. We illustrate the establishment of a tenant-aware computational network using agent-based methods, securely utilizing islands of isolated resources as a unified system.

The platform strives to deliver secure LLM services, emphasizing process and data isolation, endto-end encryption, and role-based resource authentication. This contribution aligns with the overarching goal of enabling simplified access to cutting-edge AI models and technology in support of scientific discovery.

**Comment by tgaddair** [comment]
Thanks @codybum, do you mind if we share this on social media?

**Comment by codybum** [comment]
> Thanks @codybum, do you mind if we share this on social media?

Of course, please do!
