### ISSUE TITLE
Return prompt_tokens via API

### ISSUE THREAD

**Issue by prd-tuong-nguyen** [predibase/lorax#162]
### Feature request

Currently, the API only returned the generated_tokens.
I think the API should return the prompt_tokens as number of token in requested prompt. It really useful to tracking the response speed according to the number of tokens.

### Motivation

Use to tracking the speed according the number of token

### Your contribution

:(

**Comment by tgaddair** [comment]
Thanks for raising this issue @prd-tuong-nguyen, we can definitely get this in for the next release!

**Comment by tgaddair** [comment]
Hey @prd-tuong-nguyen, this is now done following #165. Note that the Python SDK will be updated in PyPI with the next release. Until then, you can install from the repo to get the latest changes.

**Comment by prd-tuong-nguyen** [comment]
@tgaddair Awesome bro, thank you so much
