### ISSUE TITLE
Can't load local models

### ISSUE THREAD

**Issue by seanbenhur** [predibase/lorax#164]
### System Info

{"model_id":"mistralai/Mistral-7B-Instruct-v0.1","model_sha":"9ab9e76e2b09f9f29ea2d56aa5bd139e4445c59e","model_dtype":"torch.float16","model_device_type":"cuda","model_pipeline_tag":"text-generation","max_concurrent_requests":128,"max_best_of":2,"max_stop_sequences":4,"max_input_length":1024,"max_total_tokens":2048,"waiting_served_ratio":1.2,"max_batch_total_tokens":46208,"max_waiting_tokens":20,"validation_workers":2,"version":"0.1.0","sha":null,"docker_label":null}

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [X] My own modifications

### Reproduction

Hi , I am not sure whether this is a bug or my own mistake, I am trying to load an adapter from locally, but when i try i am getting 
`
{"error":"Request failed during generation: Server error: Can't find 'adapter_config.json' at '/data/models/qlora-adapter-Mistral-7B-Instruct-v0.1-gsm8k'","error_type":"generation"}`

My adapter model is inside the `data/models/ ` exactly and I am able to laod using PEFT.

I have launched my docker container like this

```
model=mistralai/Mistral-7B-Instruct-v0.1
volume=./models:/models

docker run --gpus all --shm-size 1g -p 8080:80  \
    ghcr.io/predibase/lorax:latest --model-id $model
```

and the below is the curl query
```

curl 127.0.0.1:8080/generate \
    -X POST \
    -d '{"inputs": "[INST] Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May? [/INST]", "parameters": {"max_new_tokens": 64, "adapter_id": "models/qlora-adapter-Mistral-7B-Instruct-v0.1-gsm8k","adapter_source":"local"}}' \
    -H 'Content-Type: application/json'
```

I also tried using the complete path, but still I got the same error

### Expected behavior

The server should provide the completions.

Please provide me some detailed info on how to load the local model

**Comment by tgaddair** [comment]
Hey @seanbenhur, it looks like the issue is with the `docker run` command. The local `./models` directory isn't being mounted correctly into the container. Try this instead:

```
volume=./models
docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data  \
    ghcr.io/predibase/lorax:latest --model-id $model
```

Not I used `/data` here instead of `/models` as that is the default location for the HuggingFace cache within the image.

In your request, I would also suggest providing an absolute path to the adapter:

```
"adapter_id": "/data/qlora-adapter-Mistral-7B-Instruct-v0.1-gsm8k"
```

**Comment by seanbenhur** [comment]
Thanks, I am able to solve the issue
