### ISSUE TITLE
Local Installation failed for server

### ISSUE THREAD

**Issue by asingh9530** [predibase/lorax#166]
### System Info

lorax-version - N/A
Platform - Apple M2 pro
OS - Ventura 13.2.1
Python version - 3.10

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

- Just run either `make` or `make install-server`

Throws following error
<img width="1048" alt="Screenshot 2024-01-09 at 10 40 01 PM" src="https://github.com/predibase/lorax/assets/16730377/0fe0a49d-59ef-460f-b057-0afef53e0821">

This is originating from pkg `stanford-stk`. 

one possible way to by-pass this error is to first manually install `torch` and then use `make` 

### Expected behavior

Ideally it should install all pkgs.

**Comment by tgaddair** [comment]
Hey @asingh9530, thanks for reporting this issue. It looks like the reason we aren't catching this in CI is that we remove `stanford-stk` from our dependencies for unit tests, as it requires GPUs to run:

https://github.com/predibase/lorax/blob/main/.github/workflows/tests.yaml#L66C20-L67

One fix here would be to modify the `install:` command in `server/Makefile` to install pytorch, as you said. I believe this should be safe as we do not run `make install` in the Docker image build, so there should be no risk to accidentally overriding the pytorch version.

Are you interested in putting together a PR?

**Comment by asingh9530** [comment]
@tgaddair Yeah I caught that, will add a PR to fix it. 🙂

**Comment by tgaddair** [comment]
Awesome, thank you!
