### ISSUE TITLE
Triton installation failed

### ISSUE THREAD

**Issue by asingh9530** [predibase/lorax#167]
### System Info

lorax-version - N/A
Platform - Apple M2 pro
OS - Ventura 13.2.1
Python version - 3.10

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

- This can be easily reproduced using `make install-server`.

Since triton is not supported for windows or mac as of now even binaries [here](https://pypi.org/project/triton/2.1.0/#files) confirms it but is a dependency. So just wanted to know is the team have any work around for this if wanted to test locally.

### Expected behavior

No expected behaviour, since this is not a bug.

**Comment by tgaddair** [comment]
Hey @asingh9530, it looks like triton is only required because of `stanford-stk`, which I believe would not work on macos anyway. So I believe the right fix here would be to modify the poetry config to exclude `stanford-stk` and all its dependencies if we're on windows or macos.

**Comment by asingh9530** [comment]
Agreed @tgaddair as currently triton team is working on making it available on macos but it will take time also it will be buggy. 

Note - I only reported this for pypi but it is possible to build in from scratch on local tried and it is success so yeah this issue is limited to pip installation not with build.

**Comment by asingh9530** [comment]
Agreed @tgaddair as currently triton team is working on making it available on macos but it will take time also it will be buggy. 

Note - I only reported this for pypi but it is possible to build in from scratch on local tried and it is success so yeah this issue is limited to pip installation not with build.

I will raise a PR shortly to fix this.

**Comment by tgaddair** [comment]
Hey @asingh9530, sorry I missed your last message! I put together #169 which I believe should address the issue. Please take a look when you get a chance.

**Comment by asingh9530** [comment]
@tgaddair No worries the PR looks good to me.
