### ISSUE TITLE
Incompatible Response returned from OpenAI Endpoint - Minor Bug 

### ISSUE THREAD

**Issue by AdithyanI** [predibase/lorax#183]
### System Info

The latest docker image on the branch. Image ID : *1b3. The latest as of today.

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

The OpenAI compatible endpoints works fine. But the response returned is in **incorrect format**. 
Specifically, only see `text` field in the following JSON. This is the one returned by lorax. 

```
<OpenAIObject at 0x16e9ee810> JSON: {
  "index": 0,
  "text": "{'title': \"Ketogenic diet, a powerful tool for mental health, influences brain met",
  "logprobs": null,
  "finish_reason": null
}
```

But the entire text field should be removed and it should be look like so : 

```
    "message": {
      "role": "assistant",
      "content": "{'title': \"Ketogenic diet, a powerful tool for mental health, influences brain met",
    },
    
```

The text shoudl be simply wrapped up in a message field. This is the official OpenAI response format. For more details see this : https://platform.openai.com/docs/api-reference/chat

    

### Expected behavior

A full right response is attached here. I just want the text field to be swapped with message field. The rest of the field is okay for now. This will enable to use this as a drop in replacement for OpenAI API. 

```
{
  "id": "chatcmpl-123",
  "object": "chat.completion",
  "created": 1677652288,
  "model": "gpt-3.5-turbo-0613",
  "system_fingerprint": "fp_44709d6fcb",
  "choices": [{
    "index": 0,
    "message": {
      "role": "assistant",
      "content": "\n\nHello there, how may I assist you today?",
    },
    "logprobs": null,
    "finish_reason": "stop"
  }],
  "usage": {
    "prompt_tokens": 9,
    "completion_tokens": 12,
    "total_tokens": 21
  }
}
```

I am happy to fix it and send a PR. If you point me to the right place in the code too :) 
I am new to this, so happy to contribute.

**Comment by tgaddair** [comment]
Thanks for raising this issue @AdithyanI! Could you take a look at #184 and let me know if it addresses the issue?
