### ISSUE TITLE
Add support for 'eetq' quantization format

### ISSUE THREAD

**Issue by abhibst** [predibase/lorax#190]
### System Info

docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/predibase/lorax:latest --model-id $model --num-shard $num_shard --sharded true --max-total-tokens 16000 --max-input-length 15999 --max-batch-prefill-tokens 15999 --quantize eetq

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

error: invalid value 'eetq' for '--quantize <QUANTIZE>'
  [possible values: bitsandbytes, gptq]

### Expected behavior

it should run with "eetq" as a --quantize option . As TGI do support this quantised option

**Comment by tgaddair** [comment]
Hey @abhibst, we do not support eetq at this time, but happy to look into adding it. Is there a reason you're interested in eetq in particular? I'm not familiar with this format.

cc @flozi00 who has been exploring various quantization formats.

**Comment by flozi00** [comment]
Should be easy, can start an PR when hqq and marlin are finished

**Comment by abhibst** [comment]
as eetq-> 8 bit quantization and it Should be a drop-in replacement to bitsandbytes with much better performance.  there is no specific need at this time but i did experimented with it and found it is not supported. 
Thanks

**Comment by tgaddair** [comment]
Looks like there was a build failure due to missing cutlass submodule:

```
#55 5.531 In file included from /usr/src/eetq/csrc/cutlass_kernels/fpA_intB_gemm_wrapper.cu:7:
#55 5.531 /usr/src/eetq/csrc/cutlass_kernels/fpA_intB_gemm.h:7:10: fatal error: cutlass/numeric_types.h: No such file or directory
#55 5.531     7 | #include "cutlass/numeric_types.h"
#55 5.531       |          ^~~~~~~~~~~~~~~~~~~~~~~~~
#55 5.531 compilation terminated.
#55 ...
```

@flozi00 will revert the commit for now.

**Comment by flozi00** [comment]
yeah, wasnt tested, will ping you for review when its ready
Sorry for not having it marked as WIP

**Comment by abhibst** [comment]
is it available with the "lorax:latest" ? As i am still having issues using it . Thanks
