### ISSUE TITLE
Using local adapter via OpenAI API

### ISSUE THREAD

**Issue by prd-tuong-nguyen** [predibase/lorax#199]
### Feature request

When using the original endpoint, I can pass the adapter_source as "local" to load adapter from local directory.
How can I do it with OpenAI endpoint?
I have try pass `--adapter-source local` when run docker but it's still not working 

### Motivation

Load local adapter

### Your contribution

.

**Comment by tgaddair** [comment]
Hey @prd-tuong-nguyen, I'd be happy to add support for this. There are two ways I could think to do it:

1. Allow the user to set the default adapter source during initialization, as you were trying to do.
2. Allow the user to provide the adapter source as a request parameter to the OpenAI client using the `extra_body` param here: https://github.com/openai/openai-python/blob/main/src/openai/resources/chat/completions.py#L645

Both could work. I think being able to set a default adapter source is a good idea in general, though. So happy to take that on first.

**Comment by prd-tuong-nguyen** [comment]
@tgaddair thank u for your quick reply,
I agree with you that setting the default adapter source is the good way to start.
I'm here to waiting that amazing feature <3

**Comment by tgaddair** [comment]
Hey @prd-tuong-nguyen, we just landed #223 which should hopefully address this issue. Let us know if there are any issues!

**Comment by prd-tuong-nguyen** [comment]
@tgaddair amazing, thank u
