### ISSUE TITLE
Support speculative decoding options per request

### ISSUE THREAD

**Issue by tgaddair** [predibase/lorax#205]
Medusa is a good one as it is itself an adapter and we can have a different Medusa head per adapter. But others that don't require fine-tuning would be useful as well:

https://github.com/apoorvumang/prompt-lookup-decoding

**Comment by AdithyanI** [comment]
Super interested in this! Thank for picking this up.

**Comment by abhibst** [comment]
Thanks @tgaddair

**Comment by DavidPeleg6** [comment]
thanks! @tgaddair
