### ISSUE TITLE
Openai model name fallback

### ISSUE THREAD

**Issue by flozi00** [predibase/lorax#214]
### System Info

Regarding to this pr: https://github.com/huggingface/chat-ui/pull/755

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

Send space as model name or something what is not existing on hub 

### Expected behavior

Using base model as fallback

**Comment by tgaddair** [comment]
One option someone suggested was to allow the user to provide the full base model ID in the model name, would that work?

So the user could say:

```
model="mistralai/Mistral-7B-Instruct-v0.1"  # uses base model

model="alignment-handbook/zephyr-7b-dpo-lora"  # uses adapter
```

**Comment by flozi00** [comment]
I will try it this evening

Maybe a simple strip of the string would already fix it ?
Not sure about the user experience if there are to much hidden fallbacks.
If there is just a type at the id it should still return an error
