### ISSUE TITLE
Returned from OpenAI compatible Endpoint

### ISSUE THREAD

**Issue by abhibst** [predibase/lorax#215]
### System Info

running it over latest loraX docker

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

```
from openai import OpenAI

client = OpenAI(
    api_key="",
    base_url="http://127.0.0.1:8080/v1",
)

resp = client.chat.completions.create(
    model="",
    messages=[
        {
            "role": "system",
            "content": "You are a friendly chatbot who always responds in the style of a pirate",
        },
        {"role": "user", "content": "How many helicopters can a human eat in one sitting?"},
    ],
    max_tokens=100,
)
print("Response:", resp[0].choices[0].message.content)
```
This code throw the below error :

`openai.APIStatusError: Error code: 424 - {'error': 'Request failed during generation: Server error: Conversation roles must alternate user/assistant/user/assistant/...', 'error_type': 'generation'}`

I am running **Mixtral-8x7B-Instruct-v0.1** with in loraX client.

### Expected behavior

It should run as expected .

**Comment by tgaddair** [comment]
Hey @abhibst, the issue here is likely related to the chat template used by the base model. Mixtral-Instruct does not support a system role, so you would need to change your request messages to:

```
messages=[
        {"role": "user", "content": "How many helicopters can a human eat in one sitting?"},
    ],
```

**Comment by abhibisht89** [comment]
Thanks @tgaddair , got it , A format issues with mixtral instruct template . This works

**Comment by abhibst** [comment]
Thanks @tgaddair , got it and issues with the chat template for mistral . suggestion works . Thanks
