### ISSUE TITLE
No way to access private models or adapters

### ISSUE THREAD

**Issue by adi** [predibase/lorax#232]
### System Info

I couldn't find any way to pass a HuggingFace token to lorax. I looked in the docs and in the code with no success.
Is this supported?

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. Try to start lorax with any llama2 from meta
2. Notice an error like `Cannot access gated repo for url https://huggingface.co/api/models/meta-llama/Llama-2-13b-hf.`

### Expected behavior

To have an env var or a command line arg to pass a HF token to lorax

**Comment by adi** [comment]
Noticed HF_API_TOKEN is actually doing that. Closing this...

**Comment by adi** [comment]
Actually when using OpenAI compat API with private LoRAs because the docs say:
"Chat Completions v1
Using the existing OpenAI Python SDK, replace the base_url with your LoRAX endpoint with /v1 appended. The api_key can be anything, as it is unused."
you can't pass the HF_API_TOKEN to the lorax-server.

The only workaround is to make the LoRA public.

**Comment by tgaddair** [comment]
Hey @adi, good catch! This is indeed something we intended to hook up (the ability to insert an API token into the header), we can definitely update this.

cc @magdyksaleh

**Comment by magdyksaleh** [comment]
Hey! Will take a look at this and update you

**Comment by binarycrayon** [comment]
any updates? do we have a workaround with the docker approach in the mean time?

**Comment by binarycrayon** [comment]
Would love to avoid floating my HF TOKEN around in API calls. This is a security issue that would prevents me from using lorax in a production environment.

**Comment by tgaddair** [comment]
Hey @binarycrayon @adi apologies, this was actually resolved in #278, but we hadn't updated the documentation. You can now set the bearer token in the header and it will propagate to the `api_token` correctly. I can update the docs to reflect this, but the issue itself should be resolved. Let me know if you still encounter issues!
