### ISSUE TITLE
Unable to run latest dockerfile

### ISSUE THREAD

**Issue by DhruvaBansal00** [predibase/lorax#249]
### System Info

Running the latest docker container throws the following errors:

```
lorax-launcher: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by lorax-launcher)
lorax-launcher: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by lorax-launcher)
lorax-launcher: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by lorax-launcher)
```

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

docker pull ghcr.io/predibase/lorax:latest
model=mistralai/Mistral-7B-Instruct-v0.1
volume=$PWD/data

docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data \
    ghcr.io/predibase/lorax:latest --model-id $model

### Expected behavior

Docker container should run successfully.

**Comment by DhruvaBansal00** [comment]
cc: @magdyksaleh @tgaddair  might be because of the latest dockerfile changes we made

**Comment by magdyksaleh** [comment]
Taking a look

**Comment by DhruvaBansal00** [comment]
Thanks, please keep me updated, and let me know if I can help with anything!

**Comment by magdyksaleh** [comment]
Running into the same issue - doing a local build to debug

**Comment by tgaddair** [comment]
I believe the issue is the version of ubuntu. I updated rust to 1.75 and ubuntu to 22.04 in #250, and did not have any issues running the container, so hopefully this will address the issue.

**Comment by tgaddair** [comment]
@DhruvaBansal00 the latest docker image has been built with these changes. Let me know if you're still running into issues next time you get a chance to test it out. Thanks!

**Comment by DhruvaBansal00** [comment]
Thanks a lot for the quick fix @magdyksaleh and @tgaddair! The new docker container works for me. And I can confirm that loading from s3 paths also works now :)
