### ISSUE TITLE
Support repetition_penalty in OpenAI API

### ISSUE THREAD

**Issue by prd-tuong-nguyen** [predibase/lorax#287]
### Feature request

Support `repetition_penalty` in OpenAI compaitaple API

### Motivation

It's really important parameters, currently not support in OpenAI compaitaple API

### Your contribution

.

**Comment by huytuong010101** [comment]
@tgaddair Please help me check this PR: https://github.com/predibase/lorax/pull/288

**Comment by tgaddair** [comment]
Thanks for the PR @huytuong010101. Just to confirm: the ask here is to support OpenAI's [presence_penalty](https://platform.openai.com/docs/api-reference/chat/create#chat-create-presence_penalty) and map it to LoRAX's `repetition_penalty` correct?
