### ISSUE TITLE
Include logprobs for alternative, less probable tokens in the generation response

### ISSUE THREAD

**Issue by JTS22** [predibase/lorax#298]
### Feature request

For some applications it is necessary to access the full probability distribution of the tokens generated by the model's decoder head. This could be implemented by including a (size-limited) list of alternatives with every generated token in the `details` field of a response. This list would then include the `k` most probable tokens for each generation step, including the logprob and decoded text of the token.

### Motivation

Having access to the full probability distribution of the LLM decoder head allows for a more precise analysis of the model's response. For example, by comparing the logprob of the chosen token with the alternatives, we can deduce how likely the model was to pick a different option for that next token.

### Your contribution

For models based on `FlashCausalLM`, the necessary changes are implemented in #297. Here, the client parameter `return_k_alternatives` can be used to set the size of the list of alternatives that is returned with each generated token. For models based on other classes, setting this option currently has no effect.

**Comment by tgaddair** [comment]
Makes sense! Thanks for submitting a PR :)

**Comment by JTS22** [comment]
PR is now open :)
