### ISSUE TITLE
Lorax server hangs on / after prefill when total_tokens is larger than 4096 (Mistral)

### ISSUE THREAD

**Issue by LemiSt24** [predibase/lorax#316]
### System Info

Latest docker container
RTX 4090
nvidia-smi header:
NVIDIA-SMI 535.161.07             Driver Version: 535.161.07   CUDA Version: 12.2
Model Tag: DiscoResearch/DiscoLM_German_7b_v1

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. Deploy the docker container using the DiscoResearch/DiscoLM_German_7b_v1 (mistral) model using a MAX_TOTAL_TOKENS value above 4096
2. Observe the logs.

### Expected behavior

The server should start up normally.

When using MAX_TOTAL_TOKENS=4096, everything works as expected. However, as soon as I set this value higher, the server can not get past "warming up model".

Looking at the GPU usage shows that some operation is happening and either completing or failing, with the usage being around 80% for some time until it drops to zero. However, unlike when the max length is set to <=4096, the server is not reachable after this drop and no log is printed after "warming up model".

Am I doing or understanding something wrong?

**Comment by tgaddair** [comment]
Hey @LemiSt24, the issue may be related to your card not having enough memory for the larger total tokens value. But as a quick test, could you try running with the following LoRAX params:

```
--max-input-length 8000 --max-total-tokens 8192 --max-batch-prefill-tokens 8192
```

I ran a quick test on my side with these values (on A100 w/ 40GB VRAM) and didn't have any issues. Let me know if you still see the same hanging effect.
