### ISSUE TITLE
Performance drop when using a LoRA Adapter

### ISSUE THREAD

**Issue by oscarjohansson94** [predibase/lorax#333]
Hello! 

## Introduction
I am benchmarking LoRAX with and without a LoRA adapter and I want to double check some results. 

##  Hardware
Running a single GPU, L40S with 48 GB of graphical memory. 

## Launcher Parameters
```
        --model-id
        - "Open-Orca/Mistral-7B-OpenOrca"
        - --max-input-length
        - "512"
        - --max-total-tokens # max-input-length + max-new-tokens (per batch)
        - "768"
        - --max-batch-total-tokens # batch-size * max-total-tokens
        - "1536"
        - --max-batch-prefill-tokens # batch-size * max-input-length
        - "1024"
        - --sharded
        - "false"
        - --adapter-cycle-time-s
        - "3600"
```
 
## Benchmark
I am running the same prompt 100 times and averaging tokens per second for an entire run.
The prompt sent in are 428 tokens, and I generate around 50-70 tokens. 

The parameters in the call are:
```
        "parameters": {
            "apply_chat_template": True,
            "max_new_tokens": 256,
            "adapter_id": lora_adapter,
            "adapter_source": "local",
            "details": True,
        },
```

I make sure the adapter is already loaded before the benchmark.

## Result
With LoRA adapter:  ~35 tokens / second
Without LoRA adapter: ~69 tokens /second

## Question
Is this performance drop expected when using a LoRA adapter?

**Comment by bi1101** [comment]
Hi, I also noticed this on the Predibase platform and an independent LoraX instance. I think this is expected but would love to find out for sure too!

**Comment by tgaddair** [comment]
Hey @oscarjohansson94 @bi1101 a 50% reduction in throughput is a big drop. We do observe some decrease in throughput going from 0 to 1 adapters (as it introduces more layers / kernel calls), but usually on the order maybe a 10-20% reduction in throughput. Though it will depend in large part on the rank of the LoRA. Larger ranks will have more of an effect on reducing throughput.

We're definitely looking into ways to mitigate this, notably fusing the LoRA computation with the base layer.

**Comment by oscarjohansson94** [comment]
@tgaddair Thanks for your answer!

This adapter has a rank of 32. At what range of ranks do you observe 10-20 % reduction?

**Comment by tgaddair** [comment]
Hey @oscarjohansson94 @bi1101 , we just landed #464 which should speed up LoRA inference considerably when going from 0 to 1 adapters. Please give it a shot and let me know how it goes!

**Comment by oscarjohansson94** [comment]
@tgaddair This is awesome news! Thanks for this! Can't wait to test it out, when can we expect a new release to dockerhub?

**Comment by tgaddair** [comment]
Hey @oscarjohansson94, it's available in the most recent `main` tagged Docker image:

https://github.com/predibase/lorax/pkgs/container/lorax/215772240?tag=d54aded

**Comment by tgaddair** [comment]
Also, for best performance, we suggest running with `--compile` set in the initialization arguments.

**Comment by thincal** [comment]
> Also, for best performance, we suggest running with `--compile` set in the initialization arguments.

But compile doesn't work with multiple cards inference ?

**Comment by thincal** [comment]
Also will the fix improve the inference speed when going from 1 to N adapters ?
