### ISSUE TITLE
Expose ignore_eos_token on /generate and/or /v1/completions endpoints

### ISSUE THREAD

**Issue by martinbomio** [predibase/lorax#337]
### Feature request

Hi! Seems like internally, the lorax gRPC server allows setting [ignore_eos_token](https://github.com/predibase/lorax/blob/431ae616c5850b4b02c08d3a75fb6d2e85209344/proto/generate.proto#L91), but there's no way to set that param in the /generate endpoint of the router. 

### Motivation

This parameter is useful for benchmarking and being able to consistently and correctly compare runs.

### Your contribution

Would need some guidance but could contribute it

**Comment by tgaddair** [comment]
Hey @martinbomio, thanks for the feature request! This should be a pretty simple one to add. I can definitely take a look soon if no one else picks it up first.

**Comment by martinbomio** [comment]
@tgaddair @jeffreyftang thanks for the quick addition! When could we expect to have this released? (we are using the docker image right now)

**Comment by tgaddair** [comment]
Hey @martinbomio, this should be available in the `latest` docker image to try out now :)

Let me know if you need a new version of the Python client to be pushed to PyPI.

**Comment by martinbomio** [comment]
@tgaddair that's great!

I tested passing `ignore_eos_token` to the openai compatible api `/v1/completions` and I still do not get the expected output tokens on some prompts. Is this expected? I can always switch to the /generate one and try

**Comment by tgaddair** [comment]
Hey @martinbomio , I think the current implementation didn't update the OpenAI endpoints as this param isn't native to their spec. 

@jeffreyftang   what do you think about adding this param to the OpenAI endpoints as well?

**Comment by jeffreyftang** [comment]
> I think the current implementation didn't update the OpenAI endpoints as this param isn't native to their spec.

Yep, that was my reasoning. However, happy to add to the OpenAI endpoints as well so long as we're not concerned with going beyond the OpenAI spec.

**Comment by martinbomio** [comment]
@jeffreyftang thanks for the quick PR! Would you mind sharing which base model you used for the example you posted in this PR https://github.com/predibase/lorax/pull/340? I am trying the latest version and I can't seem get the max tokens on certain prompts even if the `ignore_eos_token` is set

**Comment by martinbomio** [comment]
nvm, I can confirm it is working as expected!

**Comment by jeffreyftang** [comment]
Glad it's working! For posterity, I was using `mistralai/Mistral-7B-Instruct-v0.1`.
