### ISSUE TITLE
Add HF authentication instructions to lorax-launcher docs

### ISSUE THREAD

**Issue by JamsheedMistri** [predibase/lorax#451]
On the [LoRAX launcher docs page](https://loraexchange.ai/reference/launcher/), a `MODEL_ID` attribute is accepted. However, if the model on Huggingface requires authentication, the current docs provide no solution for providing a Huggingface API token to authenticate this LoRAX launcher request.

Instructions on how to provide a HF token can be found [here](https://huggingface.co/docs/text-generation-inference/en/basic_tutorials/gated_model_access). Perhaps adding something like this on the LoRAX launcher page would be helpful.

**Comment by binarycrayon** [comment]
Did you verify this approach work? 
I am getting 401 Client Error from lorax server when trying to retrieve gated lora, with 
`-e HUGGING_FACE_HUB_TOKEN=$HF_TOKEN`

**Comment by JamsheedMistri** [comment]
This code works for me:
```yaml
envs:
  MODEL_ID: my_model
  HUGGING_FACE_HUB_TOKEN: my_token

run: |
  docker run --gpus all \
    --shm-size 1g \
    -p 8080:80 \
    -e HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN \
    ghcr.io/predibase/lorax:latest \
    --model-id $MODEL_ID
```

If I remove the `-e` flag it no longer works.

**Comment by binarycrayon** [comment]
thanks for confirming, I'll double check my token and my setup

**Comment by binarycrayon** [comment]
it is still failing for me. Downloading a gated model work, but loading a gated lora does not.

Looks like it's failing at https://github.com/predibase/lorax/blob/157c97de3d1142e23f0d79f963147a29193f5bb6/server/lorax_server/adapters/utils.py#L20

I'm trying to figure out where they get the auth token from

**Comment by JamsheedMistri** [comment]
Ah yes, I only tested with a gated model, not a gated adapter.

**Comment by tgaddair** [comment]
Hey @binarycrayon, for adapters you can pass in the `api_token` param in the request for now. Although setting a token in the environment should apply that to all requests by default.

**Comment by seanbenhur** [comment]
@tgaddair 

i am trying to pass my token via `-e` flag but it is not getting recognized

This is my code

```bash
model=meta-llama/Meta-Llama-3-8B 
#the volume shold be changed according to the path where the adopter lies
volume=/home/ubuntu/ai-for-ops/llm_experiments/nl2elk_v2/checkpoints/llama3_8b_aimlsystems_conf_128_len_checkpoint_621
    
docker run --gpus all --shm-size 1g -p 5000:80 -v $volume:/data/ \
    hub.comcast.net/appliedai/lorax:v0.1 --model-id $model -e hf_*****
```
