### ISSUE TITLE
Problem with quantize model

### ISSUE THREAD

**Issue by prd-tuong-nguyen** [predibase/lorax#85]
### System Info

Can you tell me abit about how to serve model in 4bit quantize mode?
I added the `--quantize bitsandbytes-nf4` when run docker container but nothing change, the GPU memory keep the same

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. `docker run --gpus all --shm-size 1g-p 8080:80 -v ./ckpts:/data ghcr.io/predibase/lorax:latest --model-id /data/OpenHermes-2-7B-base-2.3 --quantize bitsandbytes-nf4`

### Expected behavior

Reduce the GPU memory

**Comment by flozi00** [comment]
Do you measure before or after warmup?

With the start up the kv cache gets reserved, with quantited model there is more memory for cache, but the total used memory is the same.
You could limit the available memory by an argument

**Comment by tgaddair** [comment]
Hey @prd-tuong-nguyen, as @flozi00 said this is likely due to the warmup phase, where we allocate additional memory in advance for batching to avoid having to allocate it on the fly during inference.

For example, here's the memory usage reported by `nvidia-smi` when running with nf4 quantization using mistral-7b before warmup:

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-PCIE-40GB          On  | 00000000:11:00.0 Off |                    0 |
| N/A   27C    P0              54W / 250W |   5011MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
```

And here are the results after warmup:

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-PCIE-40GB          On  | 00000000:11:00.0 Off |                    0 |
| N/A   27C    P0              54W / 250W |  38911MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-PCIE-40GB          On  | 00000000:13:00.0 Off |                    0 |
| N/A   28C    P0              55W / 250W |      7MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
```

As you can see, lorax will use as much memory as it can get away to maximize the batch size.

**Comment by prd-tuong-nguyen** [comment]
@flozi00 , @tgaddair Oh thanks for your fast reply, I see that the memory before warming up is lower then after that.
Can I reduce the `additional memory for batching` , in that way I can serve multi-instance in the same GPU.

**Comment by prd-tuong-nguyen** [comment]
Resolved by edit `cuda_memory_fraction`, thank you <3
